### ISSUE TITLE
md5sum failed :(

### ISSUE THREAD

**Issue by smaksimovic** [sixhop/AutoMySQLBackup#1]
Attempted to run installer after cloning SSH repo, received an "md5sum failed :(" message for each file in the check. Worked around the issue by regenerating the md5sums of each file in the check (not ideal) and replacing them in the install.sh file. Running CentOS 6.8 (Final).

**Comment by inbaz** [comment]
Hi, I didn't look into the install.sh, yet. It was just the original file as it was in the original Sourceforge code. I just changed the md5sums to the correct ones.

Cheers
Andi

**Comment by smaksimovic** [comment]
Fantastic, thanks!
