### ISSUE TITLE
Hourly Backups?

### ISSUE THREAD

**Issue by TomasHurtz** [sixhop/AutoMySQLBackup#10]
How can I configure hourly backups for a specific DB?

I have daily and monthly configured for several DBs - I just want one specific DB to backup more regularly and I'm fine with the hourly backup over-writing the previous one.

**Comment by inbaz** [comment]
You can run the automysqlbackup script per cron once per hour. Then you'll get a backup every hour in the daily directory.
Maybe this is a feature for one of the next versions.

**Comment by inbaz** [comment]
If you have any further questions or issues feel free to reopen this issue or create a new one.

**Comment by djkgamc** [comment]
This also adds a backup once per hour to the weekly/monthly backups though

**Comment by solaceten** [comment]
yes, but if you have multiple databases and only want one backed up every hour, and the rest once per week, you have to duplicate the script so that you can isolate the DBs - would be nice to have a switch in the file somehow
