### ISSUE TITLE
retry X times on failures

### ISSUE THREAD

**Issue by lzecca78** [sixhop/AutoMySQLBackup#16]
Hi, should be a good feature the possibility to add a retry option customizable with a parameter like CONFIG_retries_on_failure=3 , in this way if a backup fails for a network partitioning or whatever reason, it will retry to re-execute the task max ${CONFIG_retries_on_failure} times

**Comment by inbaz** [comment]
Why not using a small wrapper script? I didn't try it, but it's a start:

```
#!/bin/sh

BACKUP_COUNT=0
while [ "$BACKUP_COUNT" -lt 3 ]; do
    /usr/local/bin/automysqlbackup
    if [ "$?" = 0 ]; then
        break
    fi
    BACKUP_COUNT=$((BACKUP_COUNT + 1))
done
```
