### ISSUE TITLE
Single brackets in line 473

### ISSUE THREAD

**Issue by rhopfer** [sixhop/AutoMySQLBackup#2]
`/usr/local/bin/automysqlbackup: line 473: [: : integer expression expected`

`- if [ "$NODOT_VER" -ge 56 ]; then`
`+ if [[ "$NODOT_VER" -ge 56 ]]; then`

**Comment by inbaz** [comment]
Can you tell me on which system you're running this version of automysqlbackup? For me on CentOS it's working quite well with single brackets.

Answers in german are also possible. :)
Antworten auf Deutsch sind auch möglich. :)

**Comment by inbaz** [comment]
Ah, are you using the actual master branch? If so, please update your repository. I changed a thing, commited it but there was an error in it. I will have a look that the releases will work. So if you're using this tool for a production server, please use 3.0.2 at the moment.

**Comment by rhopfer** [comment]
Richtig, hab den master branch getestet, hab ich vergessen dazu zu schreiben. Mit dem Update funktioniert alles.
