### ISSUE TITLE
MariaDB doesn't honor --login-path

### ISSUE THREAD

**Issue by NiceGuyIT** [sixhop/AutoMySQLBackup#20]
Per the [docs](https://mariadb.com/kb/en/library/mysql_config_editor-compatibility/), MariaDB doesn't support the `--login-path` option. It would be nice if the README.md made note of this.

**Comment by inbaz** [comment]
Would you like to make an example how you would like to read it in the README.md?

**Comment by robertoschwald** [comment]
The PR should be merged imho.

**Comment by inbaz** [comment]
I've merged the PR.
