### ISSUE TITLE
[Bug] ERROR 2013 (HY000) at line 1: Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by lqdung1992** [sixhop/AutoMySQLBackup#23]
I got the error after I finished (though the backup was successful)

Run command `sudo /usr/local/bin/automysqlbackup`:
![image](https://user-images.githubusercontent.com/36109121/42453972-8386bf24-83b8-11e8-88aa-d735fbef2f9f.png)

Log `/var/log/Backup_Post_Pre_log`:

![image](https://user-images.githubusercontent.com/36109121/42453924-5b178cbc-83b8-11e8-9374-ebdde393d577.png)

My environment:
NAME="Amazon Linux AMI"
ID="amzn"
ID_LIKE="rhel fedora"
PRETTY_NAME="Amazon Linux AMI 2018.03"
Mysql5.6

**Comment by lqdung1992** [comment]
I've fixed it.
Because of some functions on the CONFIG_postbackup event. it causes this error.

**Comment by pmvbajpai** [comment]
Could you please let me know the exact issue and its solution as I am facing the same. Thanks in advance.
