### ISSUE TITLE
line 873: 6: Bad file descriptor

### ISSUE THREAD

**Issue by modir** [sixhop/AutoMySQLBackup#28]
I just downloaded the newest version and I got these error messages:

```
/usr/local/bin/automysqlbackup: line 873: 6: Bad file descriptor
/usr/local/bin/automysqlbackup: line 874: 7: Bad file descriptor
```

**Comment by inbaz** [comment]
Can you please tell me which OS you're using for automysqlbackup?

**Comment by modir** [comment]
CentOS 7

**Comment by inbaz** [comment]
Are you executing automysqlbackup as root and can you please check if SELinux is active? Maybe this will prohibit the file descriptor handling. Is this the only error or are there errors before? Could you please execute automysqlbackup using bash -x and send the log?

**Comment by inbaz** [comment]
Nothing heard for a longer time. I will close this issue. Feel free to reopen it if the issue still exists for you.

**Comment by shanerbaner82** [comment]
I am installing this inside of Docker (Ubuntu 18.04) like so:

```
RUN sudo mkdir /usr/local/src/automysqlbackup &&\
    cd /usr/local/src/automysqlbackup &&\
    sudo wget https://github.com/sixhop/AutoMySQLBackup/archive/3.0.7.tar.gz &&\
    sudo tar xvzf 3.0.7.tar.gz &&\
    cd AutoMySQLBackup-3.0.7 &&\
    sudo chmod a+x install.sh &&\
    sudo sh install.sh
```

When I ssh into the box and run `automysqlbackup` as root I get this same issue:

```
root@6d533a04eff1:~# automysqlbackup 
does not exist. Exiting.
Note: Supplied more than one argument, ignoring ALL arguments - using default and global config file only.
Error: No basedir found, i.e.
/usr/local/bin/automysqlbackup: line 873: 6: Bad file descriptor
/usr/local/bin/automysqlbackup: line 874: 7: Bad file descriptor
Skipping normal output methods, since the program exited before any log files could be created.
```

I feel like I am missing some big step.... any help here is appreciated.

**Comment by andyrue** [comment]
I got this error when my `CONFIG_backup_dir` was pointing to a folder that didn't exist.
