### ISSUE TITLE
Improve text in the help

### ISSUE THREAD

**Issue by jannyba** [sixhop/AutoMySQLBackup#33]
Hi

as a new user I have no idea what means this: "-b      Use backup method."

- please explain it in the readme and in the short help.
I don't understand which backup methods are available to choose from, or if this is a switch and when I don't enable this option what will happen, it will not do the backup or..?

- you should mention in the README file what permisions are required for the account performing the backups, because when people don't want enter plain root password in the config file and they want create separate database account just for the backups

thx

**Comment by inbaz** [comment]
1. You can hand over a separate config file and it looks like the -b switch is needed to run the backup method then. Looks like this enables to create full backups from diffs without backing up the databases in a run. That's part of the script I've taken over from sourceforge.

2. the system user that runs the script and the user that accesses the database are two different things. The file permissions always need to be in a way that the user who runs the script can write into the directory the backup should go to. Regardless with which database user the backup is created.

**Comment by jannyba** [comment]
1.so can you create Pull request and add this explanation in command line -h and readme file?

2. the backup script is started by sudo crontab, that is not an issue, but I do not want enter mysql's root password in the config file, that is what I asked for what permissions the mysql user need to create the backup (which I expect will be mostly read only).
