### ISSUE TITLE
Ubuntu 18 (OpenSSL 1.1.1) Warning "deprecated key derivation used"

### ISSUE THREAD

**Issue by eSkiSo** [sixhop/AutoMySQLBackup#36]
> ###### WARNING ######
> Errors reported during AutoMySQLBackup execution.. Backup failed
> Error log below..
> *** WARNING : deprecated key derivation used.
> Using -iter or -pbkdf2 would be better.

I was able to bypass this by adding **-pbkdf2 -iter 1000** to the openssl encryption call:
**This:**
 _openssl enc -aes-256-cbc -e -in ${1} -out ${1}.enc -pass pass:"${CONFIG_encrypt_password}"_

**Become this:** _
openssl enc -aes-256-cbc -pbkdf2 -iter 1000 -e -in ${1} -out ${1}.enc -pass pass:"${CONFIG_encrypt_password}"_

**Comment by minkbear** [comment]
Confirm your solution work fine.

Thank you much.

**Comment by inbaz** [comment]
I added the parameter.
