### ISSUE TITLE
integer expression expected on Ubuntu 19.10

### ISSUE THREAD

**Issue by alextime** [sixhop/AutoMySQLBackup#37]
Hi, on a new Ubuntu 19.10 install I get the following error

/usr/local/bin/automysqlbackup: line 506: [: 8019 01910: integer expression expected]

Any ideas on why is this happening?

**Comment by inbaz** [comment]
Hi, were you able to solve the problem? If not, the output of ```bash -x /usr/local/bin/automysqlbackup``` would be great for debugging.

**Comment by Lange23** [comment]
Hi I have the same error.

It says:

/usr/local/bin/automysqlbackup: line 506: [: : integer expression expected
mysqldump: Got error: 1016: Can't open file: './customer24/twarenkorbperspos.frm' (errno: 24 - Too many open files) when using LOCK TABLES

I think it's related to the fact that I am handeling with too many tables.


Also zuviele Tabellen die mysqldump nicht verarbeiten kann.
Auf "--lock-tables=false" wollte ich aber mal verzichten  weil ein lock ist ja schon sinnvoll beim dump.

**Comment by BigAndini** [comment]
Haha, funny Mischung out of Deutsch and Englisch. :) Let's keep it in Englisch. That should be understandable for everybody.

The 19.10 problem is fixed with the last commit, I've added a head -1 for the VERSION search. Please have another try.

@Lange23 Your problem is another one. Maybe you should check your ulimits. That's an issue with mysqldump and too many open files rather than automysql.

**Comment by Lange23** [comment]
Hi, I raised the openfiles limit now:

`mysql> show variables like "open_files%";
+------------------+---------+
| Variable_name    | Value   |
+------------------+---------+
| open_files_limit | 1024000 |
+------------------+---------+
1 row in set (0.00 sec)`


But now I get a new error message.
Did I messed something up ?:

`root@vmd23759:~# /usr/local/bin/automysqlbackup /etc/automysqlbackup/my.server.com.conf
checking directory "/var/backups/mysql/daily" ... exists.
checking directory "/var/backups/mysql/weekly" ... exists.
checking directory "/var/backups/mysql/monthly" ... exists.
checking directory "/var/backups/mysql/latest" ... exists.
checking directory "/var/backups/mysql/tmp" ... exists.
checking directory "/var/backups/mysql/fullschema" ... exists.
checking directory "/var/backups/mysql/status" ... exists.

# Testing for installed programs
pigz ... found.
mysql ... found.
mysqldump ... found.

# Parsing databases ... done.
======================================================================
AutoMySQLBackup version 3.0
http://sourceforge.net/projects/automysqlbackup/

Backup of Database Server - localhost
Databases - databasesql10,databasesql14,databasesql17,databasesql2,databasesql29,databasesql3,databasesql34,databasesql37,databasesql38,databasesql39,databasesql40,databasesql41,databasesql42,databasesql5,froxlor,mysql,sys
Databases (monthly) - databasesql10,databasesql14,databasesql17,databasesql2,databasesql29,databasesql3,databasesql34,databasesql37,databasesql38,databasesql39,databasesql40,databasesql41,databasesql42,databasesql5,froxlor,mysql,sys
======================================================================
======================================================================
Dump full schema.

Rotating 4 month backups for

======================================================================

======================================================================
Dump status.

Rotating 4 month backups for

======================================================================

Backup Start Time Wed May 20 10:20:42 CEST 2020
======================================================================
Daily Backup ...

Daily Backup of Database ( database10 )
Rotating 6 day backups for database10
----------------------------------------------------------------------
Daily Backup of Database ( database14 )
Rotating 6 day backups for database14
----------------------------------------------------------------------
Daily Backup of Database ( database17 )
Rotating 6 day backups for database17
----------------------------------------------------------------------
Daily Backup of Database ( database2 )
Rotating 6 day backups for databasel2
----------------------------------------------------------------------
Daily Backup of Database ( database29 )
Rotating 6 day backups for database29
----------------------------------------------------------------------
Daily Backup of Database ( database3 )
Rotating 6 day backups for database3
----------------------------------------------------------------------
Daily Backup of Database ( database34 )
Rotating 6 day backups for database34
----------------------------------------------------------------------
Daily Backup of Database ( database37 )
Rotating 6 day backups for database37
----------------------------------------------------------------------
Daily Backup of Database ( databasel38 )
Rotating 6 day backups for databasel38
----------------------------------------------------------------------
Daily Backup of Database ( database39 )
Rotating 6 day backups for databasel39
----------------------------------------------------------------------
Daily Backup of Database ( database40 )
Rotating 6 day backups for database40
----------------------------------------------------------------------
Daily Backup of Database ( database41 )
Rotating 6 day backups for databasel41
----------------------------------------------------------------------
Daily Backup of Database ( database42 )
Rotating 6 day backups for database42
----------------------------------------------------------------------
Daily Backup of Database ( database5 )
Rotating 6 day backups for database5
----------------------------------------------------------------------
Daily Backup of Database ( froxlor )
Rotating 6 day backups for froxlor
----------------------------------------------------------------------
Daily Backup of Database ( mysql )
Rotating 6 day backups for mysql
----------------------------------------------------------------------
Daily Backup of Database ( sys )
Rotating 6 day backups for sys
----------------------------------------------------------------------

Backup End Time Wed May 20 10:20:56 CEST 2020
======================================================================
Total disk space used for backup storage...
Size - Location
1.5G /var/backups/mysql

======================================================================

###### WARNING ######
Errors reported during AutoMySQLBackup execution.. Backup failed
Error log below..
/usr/local/bin/automysqlbackup: line 506: [: : integer expression expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 887: [: =: unary operator expected
/usr/local/bin/automysqlbackup: line 911: [: =: unary operator expected`
