### ISSUE TITLE
integer expression expected on Ubuntu 20.04.1 LTS (MySQL 8 not working)

### ISSUE THREAD

**Issue by Esuk** [sixhop/AutoMySQLBackup#39]
I recently upgraded my dev enviroment to Ubuntu 20.04.1 LTS with MySQL 8.0.20. After this upgrade the script stopped working with the following error. (I'm using login-path method)

`/usr/local/bin/automysqlbackup: line 506: [: 8020 02004: integer expression expected`

After some investigation I found out this is from the version of MySQL and Ubuntu. 

Line 116 and 117 in automysqlbackup
```
VERSION=`mysql -V | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"`
NODOT_VER=`echo $VERSION | sed -${sed_Regex} 's/\.//g'`

```
MySQL output
`Server version: 8.0.20-0ubuntu0.20.04.1 (Ubuntu)`
Rexexp as `8020 02004` which matches the error message in line 506.

### My temporary solution

If i change the regexp in line 116 I get MySQL 8 working by removing the Ubuntu 02004 part
```
VERSION=`mysql -V | grep -oE "[1-9]+\.[0-9]+\.[0-9]+"`
```
After this change the backup works again!

Not sure this is a good solution though? It's a fix for me but you probably have a better solution that knows the rest of the script and where there can be more problems.

**Comment by BigAndini** [comment]
Thank you. I'll check that. Maybe you can have a try with 0-9 in the first place and another | head -1 at the end of the command.

**Comment by Esuk** [comment]
`grep -oE "[0-9]+\.[0-9]+\.[0-9]+" | head -1`works nicely! :D

**Comment by BigAndini** [comment]
I've added it to the code.

**Comment by Lange23** [comment]
Hi, I have Ubuntu 16.04.6 LTS \n \l and still got the error like in my Issue:

https://github.com/sixhop/AutoMySQLBackup/issues/37#issuecomment-631322876

My Log Output is in the file below.

[detail_report.txt](https://github.com/sixhop/AutoMySQLBackup/files/4656254/detail_report.txt)
