### ISSUE TITLE
install.sh fails md5sum preflight check

### ISSUE THREAD

**Issue by hysterio33** [sixhop/AutoMySQLBackup#5]
Hi,

When trying to run install.sh from AutoMySQLBackup-Master I get a md5sum failure for the automysqlbackup file.

inside the install.sh it lists the md5 as 33a3a48a418ccfa978b023cd5a8e2d0b however the hash i get for the bundled automysqlbackup file is 31e3b0fe937af7ba3c4015543cd2a848

Thanks

**Comment by inbaz** [comment]
Hey @hysterio33,

I adjusted the md5sums to be the ones from the files in the project. Could you please have a try if everything is working with 3.0.4 at your side?

Cheers
Andi

**Comment by hysterio33** [comment]
Looks good
