### ISSUE TITLE
Error: The mysql server is empty, i.e. no databases found. Check if something is wrong. Exiting.

### ISSUE THREAD

**Issue by mediavista** [sixhop/AutoMySQLBackup#6]
testing on mariadb 10.1 and failed
i have set mysql server with root and root mysql password and get this error:

automysqlbackup]# /usr/local/bin/automysqlbackup /etc/automysqlbackup/automysqlbackup.conf
checking directory "/var/backup/db/daily" ... exists.
checking directory "/var/backup/db/weekly" ... exists.
checking directory "/var/backup/db/monthly" ... exists.
checking directory "/var/backup/db/latest" ... exists.
checking directory "/var/backup/db/tmp" ... exists.
checking directory "/var/backup/db/fullschema" ... exists.
checking directory "/var/backup/db/status" ... exists.

# Testing for installed programs
pigz ... found.
mysql ... found.
mysqldump ... found.

# Parsing databases ... Note: Parsed config file /etc/automysqlbackup/automysqlbackup.conf.
Error: The mysql server is empty, i.e. no databases found. Check if something is wrong. Exiting.

###### WARNING ######
Errors reported during AutoMySQLBackup execution.. Backup failed
Error log below..
mysql: unknown variable 'ssl-mode=REQUIRED'

**Comment by rvnz45** [comment]
uncomment and set no this line 
CONFIG_mysql_dump_usessl='no'

seems there is a bug with CONFIG_MAIL too : 
/usr/local/bin/automysqlbackup: line 184: mail: command not found

**Comment by inbaz** [comment]
Hi @rvnz45,

thank you for your reporting. You're right. I'm using the usessl='no' for all my local backups directly in the configuration. I changed that in the code so usessl='no' is used by default. Checkout 3.0.5 for this change.

For the mail part, what did you configure for CONFIG_mailcontent? The default is stdout which should not need mail. For all other options the script checks the dependencies.

**Comment by rvnz45** [comment]
this is my configure :

**Comment by inbaz** [comment]
When mail is not found, maybe install mailx, depends on which system you are.

**Comment by vgrange** [comment]
Thanks @rvnz45 you saved my day. `CONFIG_mysql_dump_usessl='no'` fixed the issue for me.

**Comment by dnjora** [comment]
This fixed my issue but I got a  new error - se below.
"mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces"

Any idea good people.

**Comment by nathanhoeller** [comment]
> 

Hey @dnjora, there was some discussion about this same issue here (https://github.com/sixhop/AutoMySQLBackup/pull/51), but no resolution at this time. I would really love to know how to solve this issue and get this error message to go away, but I haven't had the time to dig through the code.
